//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementSystem.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ManagementSystem.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AddSmall {
            get {
                object obj = ResourceManager.GetObject("AddSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon AppIcon {
            get {
                object obj = ResourceManager.GetObject("AppIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ApproveSmall {
            get {
                object obj = ResourceManager.GetObject("ApproveSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CancelSmall {
            get {
                object obj = ResourceManager.GetObject("CancelSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EditSmall {
            get {
                object obj = ResourceManager.GetObject("EditSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FilterSmall {
            get {
                object obj = ResourceManager.GetObject("FilterSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schválení inventury.
        /// </summary>
        internal static string InventoryApproveConfirmationCaption {
            get {
                return ResourceManager.GetString("InventoryApproveConfirmationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Po schválení již nebude možné inventuru upravit.
        ///Opravdu si přejete inventuru č. {0} schválit?.
        /// </summary>
        internal static string InventoryApproveConfirmationText {
            get {
                return ResourceManager.GetString("InventoryApproveConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máte neuložené změny v položkách. Přejete si je před schválením uložit?
        ///Po schválení již nebude možné inventuru č. {0} upravit..
        /// </summary>
        internal static string InventoryApproveUnsavedItemsText {
            get {
                return ResourceManager.GetString("InventoryApproveUnsavedItemsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NewSmall {
            get {
                object obj = ResourceManager.GetObject("NewSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RemoveSmall {
            get {
                object obj = ResourceManager.GetObject("RemoveSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schválení prodeje.
        /// </summary>
        internal static string SaleApproveConfirmationCaption {
            get {
                return ResourceManager.GetString("SaleApproveConfirmationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Po schválení již nebude možné prodej upravit.
        ///Opravdu si přejete prodej č. {0} schválit?.
        /// </summary>
        internal static string SaleApproveConfirmationText {
            get {
                return ResourceManager.GetString("SaleApproveConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máte neuložené změny v položkách. Přejete si je před schválením uložit?
        ///Po schválení již nebude možné prodej č. {0} upravit..
        /// </summary>
        internal static string SaleApproveUnsavedItemsText {
            get {
                return ResourceManager.GetString("SaleApproveUnsavedItemsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SaveSmall {
            get {
                object obj = ResourceManager.GetObject("SaveSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schválení příjemky.
        /// </summary>
        internal static string SupplyApproveConfirmationCaption {
            get {
                return ResourceManager.GetString("SupplyApproveConfirmationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Po schválení již nebude možné příjemku upravit.
        ///Opravdu si přejete příjemku č. {0} schválit?.
        /// </summary>
        internal static string SupplyApproveConfirmationText {
            get {
                return ResourceManager.GetString("SupplyApproveConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máte neuložené změny v položkách. Přejete si je před schválením uložit?
        ///Po schválení již nebude možné příjemku č. {0} upravit..
        /// </summary>
        internal static string SupplyApproveUnsavedItemsText {
            get {
                return ResourceManager.GetString("SupplyApproveUnsavedItemsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neuložená data.
        /// </summary>
        internal static string UnsavedData {
            get {
                return ResourceManager.GetString("UnsavedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přejete si zahodit neuložená data?.
        /// </summary>
        internal static string UnsavedDataWarning {
            get {
                return ResourceManager.GetString("UnsavedDataWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hodnota není číslo..
        /// </summary>
        internal static string ValidationInteger {
            get {
                return ResourceManager.GetString("ValidationInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text je delší než {0} znaků..
        /// </summary>
        internal static string ValidationLength {
            get {
                return ResourceManager.GetString("ValidationLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toto pole je povinné..
        /// </summary>
        internal static string ValidationMandatory {
            get {
                return ResourceManager.GetString("ValidationMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Číslo {0} již v databázi existuje..
        /// </summary>
        internal static string ValidationNumberExists {
            get {
                return ResourceManager.GetString("ValidationNumberExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hodnota není číslo menší než 32768..
        /// </summary>
        internal static string ValidationShort {
            get {
                return ResourceManager.GetString("ValidationShort", resourceCulture);
            }
        }
    }
}
